import { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Scale, Loader2, Copy, CheckCircle, Download, Building2, ChevronDown } from 'lucide-react';
import { useCreditCoach } from '@/hooks/useCreditCoach';
import { toast } from 'sonner';
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible';
import jsPDF from 'jspdf';

const DISPUTE_TYPES = [
  { value: 'not-my-account', label: 'Not my account (Identity theft)' },
  { value: 'incorrect-balance', label: 'Incorrect balance' },
  { value: 'paid-showing-open', label: 'Account paid but showing open' },
  { value: 'late-payment-error', label: 'Late payment reported incorrectly' },
  { value: 'belongs-to-other', label: 'Account belongs to someone else' },
  { value: 'duplicate-account', label: 'Duplicate account' },
];

const CREDIT_BUREAU_ADDRESSES = [
  {
    name: 'Equifax',
    address: 'Equifax Information Services LLC\nP.O. Box 740256\nAtlanta, GA 30374-0256',
  },
  {
    name: 'Experian',
    address: 'Experian\nP.O. Box 4500\nAllen, TX 75013',
  },
  {
    name: 'TransUnion',
    address: 'TransUnion LLC\nConsumer Dispute Center\nP.O. Box 2000\nChester, PA 19016',
  },
];

export function DisputeWizardCard() {
  const [disputeType, setDisputeType] = useState('');
  const [accountName, setAccountName] = useState('');
  const [copied, setCopied] = useState(false);
  const [copiedAddress, setCopiedAddress] = useState<string | null>(null);
  const [showAddresses, setShowAddresses] = useState(false);
  const { mutate: generateLetter, data, isPending } = useCreditCoach();

  const handleGenerate = () => {
    if (!disputeType) {
      toast.error('Please select an error type');
      return;
    }

    generateLetter({
      mode: 'dispute-wizard',
      data: { disputeType, accountName },
    }, {
      onSuccess: () => {
        toast.success('Dispute letter generated!');
      },
      onError: () => {
        toast.error('Failed to generate letter');
      },
    });
  };

  const handleCopy = () => {
    if (data?.result) {
      navigator.clipboard.writeText(data.result);
      setCopied(true);
      toast.success('Letter copied to clipboard!');
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleCopyAddress = (bureauName: string, address: string) => {
    navigator.clipboard.writeText(address);
    setCopiedAddress(bureauName);
    toast.success(`${bureauName} address copied!`);
    setTimeout(() => setCopiedAddress(null), 2000);
  };

  const handleDownloadPDF = () => {
    if (!data?.result) return;

    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Credit Report Dispute Letter', 14, 20);
    
    // Metadata
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, 30);
    const selectedType = DISPUTE_TYPES.find(t => t.value === disputeType)?.label || '';
    doc.text(`Dispute Type: ${selectedType}`, 14, 36);
    if (accountName) {
      doc.text(`Account: ${accountName}`, 14, 42);
    }
    
    // Letter content
    doc.setFontSize(11);
    const startY = accountName ? 52 : 46;
    const splitText = doc.splitTextToSize(data.result, 180);
    doc.text(splitText, 14, startY);
    
    // Footer
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by $ave+ Credit Command Center', 14, doc.internal.pageSize.height - 10);
    
    // Download
    const fileName = `dispute-letter-${disputeType}-${Date.now()}.pdf`;
    doc.save(fileName);
    toast.success('PDF downloaded!');
  };

  return (
    <Card className="backdrop-blur-glass bg-glass border-glass-border">
      <CardHeader>
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg bg-primary/10">
            <Scale className="h-5 w-5 text-primary" />
          </div>
          <div>
            <CardTitle>Dispute Wizard</CardTitle>
            <CardDescription>Generate FCRA-cited dispute letters</CardDescription>
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="dispute-type">Error Type</Label>
          <Select value={disputeType} onValueChange={setDisputeType}>
            <SelectTrigger id="dispute-type">
              <SelectValue placeholder="Select error type" />
            </SelectTrigger>
            <SelectContent>
              {DISPUTE_TYPES.map((type) => (
                <SelectItem key={type.value} value={type.value}>
                  {type.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        <div className="space-y-2">
          <Label htmlFor="account-name">Account Name (Optional)</Label>
          <Input
            id="account-name"
            placeholder="e.g., Chase Freedom"
            value={accountName}
            onChange={(e) => setAccountName(e.target.value)}
          />
        </div>

        <Button
          onClick={handleGenerate}
          disabled={isPending || !disputeType}
          className="w-full"
        >
          {isPending ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Generating...
            </>
          ) : (
            'Generate Dispute Letter'
          )}
        </Button>

        {data?.result && (
          <div className="space-y-4">
            <div className="space-y-3 p-4 rounded-lg bg-muted/20 border border-border">
              <div className="flex items-center justify-between">
                <p className="text-sm font-medium text-muted-foreground">Your Dispute Letter:</p>
                <div className="flex gap-2">
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={handleCopy}
                    className="h-8"
                  >
                    {copied ? (
                      <>
                        <CheckCircle className="mr-2 h-4 w-4 text-green-500" />
                        Copied!
                      </>
                    ) : (
                      <>
                        <Copy className="mr-2 h-4 w-4" />
                        Copy
                      </>
                    )}
                  </Button>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={handleDownloadPDF}
                    className="h-8"
                  >
                    <Download className="mr-2 h-4 w-4" />
                    Download PDF
                  </Button>
                </div>
              </div>
              <div className="text-sm whitespace-pre-wrap font-mono text-foreground/90 max-h-96 overflow-y-auto">
                {data.result}
              </div>
            </div>

            <Collapsible open={showAddresses} onOpenChange={setShowAddresses}>
              <CollapsibleTrigger asChild>
                <Button variant="outline" className="w-full">
                  <Building2 className="mr-2 h-4 w-4" />
                  Bureau Mailing Addresses
                  <ChevronDown className={`ml-auto h-4 w-4 transition-transform ${showAddresses ? 'rotate-180' : ''}`} />
                </Button>
              </CollapsibleTrigger>
              <CollapsibleContent className="pt-4">
                <div className="grid gap-3 md:grid-cols-3">
                  {CREDIT_BUREAU_ADDRESSES.map((bureau) => (
                    <div key={bureau.name} className="p-3 rounded-lg bg-muted/20 border border-border space-y-2">
                      <div className="flex items-center justify-between">
                        <p className="text-sm font-semibold">{bureau.name}</p>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => handleCopyAddress(bureau.name, bureau.address)}
                          className="h-7 px-2"
                        >
                          {copiedAddress === bureau.name ? (
                            <CheckCircle className="h-3 w-3 text-green-500" />
                          ) : (
                            <Copy className="h-3 w-3" />
                          )}
                        </Button>
                      </div>
                      <p className="text-xs text-muted-foreground whitespace-pre-line">
                        {bureau.address}
                      </p>
                    </div>
                  ))}
                </div>
              </CollapsibleContent>
            </Collapsible>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
