import { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { Heart, Loader2, Copy, CheckCircle, Download } from 'lucide-react';
import { useCreditCoach } from '@/hooks/useCreditCoach';
import { toast } from 'sonner';
import jsPDF from 'jspdf';

const CIRCUMSTANCES = [
  { value: 'medical', label: 'Medical Emergency' },
  { value: 'job-loss', label: 'Job Loss' },
  { value: 'tech-glitch', label: 'Tech Glitch / Autopay Failure' },
  { value: 'natural-disaster', label: 'Natural Disaster' },
  { value: 'family-emergency', label: 'Family Emergency' },
  { value: 'military', label: 'Military Deployment' },
];

const LATE_DAYS = [
  { value: '30', label: '30 days' },
  { value: '60', label: '60 days' },
  { value: '90', label: '90 days' },
];

export function GoodwillGhostwriterCard() {
  const [creditorName, setCreditorName] = useState('');
  const [circumstance, setCircumstance] = useState('');
  const [lateDays, setLateDays] = useState('');
  const [additionalContext, setAdditionalContext] = useState('');
  const [copied, setCopied] = useState(false);
  const { mutate: generateLetter, data, isPending } = useCreditCoach();

  const handleGenerate = () => {
    if (!creditorName || !circumstance || !lateDays) {
      toast.error('Please fill in all required fields');
      return;
    }

    generateLetter({
      mode: 'goodwill-ghostwriter',
      data: { 
        creditorName, 
        circumstanceType: circumstance, 
        lateDays,
        additionalContext 
      },
    }, {
      onSuccess: () => {
        toast.success('Goodwill letter generated!');
      },
      onError: () => {
        toast.error('Failed to generate letter');
      },
    });
  };

  const handleCopy = () => {
    if (data?.result) {
      navigator.clipboard.writeText(data.result);
      setCopied(true);
      toast.success('Letter copied to clipboard!');
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownloadPDF = () => {
    if (!data?.result) return;

    const doc = new jsPDF();
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Goodwill Adjustment Request', 14, 20);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, 30);
    doc.text(`Creditor: ${creditorName}`, 14, 36);
    const selectedCircumstance = CIRCUMSTANCES.find(c => c.value === circumstance)?.label || '';
    doc.text(`Circumstance: ${selectedCircumstance}`, 14, 42);
    doc.text(`Days Late: ${lateDays}`, 14, 48);
    
    doc.setFontSize(11);
    const splitText = doc.splitTextToSize(data.result, 180);
    doc.text(splitText, 14, 58);
    
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by $ave+ Credit Command Center', 14, doc.internal.pageSize.height - 10);
    
    const fileName = `goodwill-letter-${creditorName.toLowerCase().replace(/\s+/g, '-')}-${Date.now()}.pdf`;
    doc.save(fileName);
    toast.success('PDF downloaded!');
  };

  const selectedCircumstance = CIRCUMSTANCES.find(c => c.value === circumstance);

  return (
    <Card className="backdrop-blur-glass bg-glass border-glass-border">
      <CardHeader>
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg bg-pink-500/10">
            <Heart className="h-5 w-5 text-pink-500" />
          </div>
          <div>
            <CardTitle>Goodwill Ghostwriter</CardTitle>
            <CardDescription>Request forgiveness for legitimate late payments</CardDescription>
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="creditor">Creditor Name *</Label>
          <Input
            id="creditor"
            placeholder="e.g., Chase, Capital One"
            value={creditorName}
            onChange={(e) => setCreditorName(e.target.value)}
          />
        </div>

        <div className="space-y-2">
          <Label htmlFor="circumstance">Circumstance Type *</Label>
          <Select value={circumstance} onValueChange={setCircumstance}>
            <SelectTrigger id="circumstance">
              <SelectValue placeholder="Select circumstance" />
            </SelectTrigger>
            <SelectContent>
              {CIRCUMSTANCES.map((circ) => (
                <SelectItem key={circ.value} value={circ.value}>
                  {circ.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        {selectedCircumstance && (
          <div className="p-2 rounded-md bg-muted/30 border border-border">
            <p className="text-xs text-muted-foreground">
              Selected: <span className="font-medium text-foreground">{selectedCircumstance.label}</span>
            </p>
          </div>
        )}

        <div className="space-y-2">
          <Label htmlFor="late-days">How Late *</Label>
          <Select value={lateDays} onValueChange={setLateDays}>
            <SelectTrigger id="late-days">
              <SelectValue placeholder="Select days late" />
            </SelectTrigger>
            <SelectContent>
              {LATE_DAYS.map((day) => (
                <SelectItem key={day.value} value={day.value}>
                  {day.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        <div className="space-y-2">
          <Label htmlFor="context">Additional Context (Optional)</Label>
          <Textarea
            id="context"
            placeholder="Any personal details to strengthen your case..."
            value={additionalContext}
            onChange={(e) => setAdditionalContext(e.target.value)}
            rows={3}
          />
        </div>

        <Button
          onClick={handleGenerate}
          disabled={isPending || !creditorName || !circumstance || !lateDays}
          className="w-full"
        >
          {isPending ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Crafting Letter...
            </>
          ) : (
            'Generate Goodwill Letter'
          )}
        </Button>

        {data?.result && (
          <div className="space-y-3 p-4 rounded-lg bg-muted/20 border border-border">
            <div className="flex items-center justify-between">
              <p className="text-sm font-medium text-muted-foreground">Your Goodwill Letter:</p>
              <div className="flex gap-2">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleCopy}
                  className="h-8"
                >
                  {copied ? (
                    <>
                      <CheckCircle className="mr-2 h-4 w-4 text-green-500" />
                      Copied!
                    </>
                  ) : (
                    <>
                      <Copy className="mr-2 h-4 w-4" />
                      Copy
                    </>
                  )}
                </Button>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleDownloadPDF}
                  className="h-8"
                >
                  <Download className="mr-2 h-4 w-4" />
                  Download PDF
                </Button>
              </div>
            </div>
            <div className="text-sm whitespace-pre-wrap font-mono text-foreground/90 max-h-96 overflow-y-auto">
              {data.result}
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
