import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { breach, diagnosis, fixResult, incidentLog } = await req.json();

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    // Get admin users' emails from profiles
    const { data: adminUsers } = await supabase
      .from('user_roles')
      .select('user_id')
      .eq('role', 'admin');

    if (!adminUsers || adminUsers.length === 0) {
      console.log('[Hephaestus Alert] No admin users found');
      return new Response(
        JSON.stringify({ success: true, message: 'No admins to notify' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const adminIds = adminUsers.map(u => u.user_id);
    
    const { data: profiles } = await supabase
      .from('profiles')
      .select('email')
      .in('id', adminIds);

    const adminEmails = profiles?.map(p => p.email).filter(Boolean) || [];

    if (adminEmails.length === 0) {
      console.log('[Hephaestus Alert] No admin emails found');
      return new Response(
        JSON.stringify({ success: true, message: 'No admin emails configured' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Check if RESEND_API_KEY is configured
    const RESEND_API_KEY = Deno.env.get('RESEND_API_KEY');
    if (!RESEND_API_KEY) {
      console.log('[Hephaestus Alert] RESEND_API_KEY not configured, skipping email');
      return new Response(
        JSON.stringify({ success: true, message: 'Email not configured' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const severityEmoji = breach.severity === 'critical' ? '🚨' : '⚠️';
    
    for (const email of adminEmails) {
      const emailBody = {
        from: "save+ Monitoring <alerts@saveplus.app>",
        to: [email],
        subject: `${severityEmoji} Hephaestus Alert: ${breach.metric_name}`,
        html: `
          <h1>🔧 Hephaestus Auto-Fix Applied</h1>
          <h2>Incident Summary</h2>
          <ul>
            <li><strong>Metric:</strong> ${breach.metric_name}</li>
            <li><strong>Severity:</strong> ${breach.severity.toUpperCase()}</li>
            <li><strong>Current Value:</strong> ${breach.current_value}</li>
            <li><strong>Threshold:</strong> ${breach.threshold_value}</li>
            <li><strong>Time:</strong> ${new Date().toISOString()}</li>
          </ul>
          
          <h2>AI Diagnosis</h2>
          <pre>${diagnosis}</pre>
          
          <h2>Action Taken</h2>
          <ul>
            <li><strong>Type:</strong> ${fixResult.action_type}</li>
            <li><strong>Description:</strong> ${fixResult.description}</li>
            <li><strong>Fix Applied:</strong> ${fixResult.fix_applied}</li>
            <li><strong>Status:</strong> ${fixResult.successful ? '✅ Success' : '❌ Failed'}</li>
            <li><strong>Execution Time:</strong> ${fixResult.execution_time}ms</li>
          </ul>
          
          <hr>
          <p><em>This alert was automatically generated by Hephaestus (Backend Fixer Agent)</em></p>
        `,
      };

      const emailResponse = await fetch('https://api.resend.com/emails', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${RESEND_API_KEY}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(emailBody),
      });

      if (!emailResponse.ok) {
        console.error('[Hephaestus Alert] Email send failed:', await emailResponse.text());
      }
    }

    console.log(`[Hephaestus Alert] Sent to ${adminEmails.length} admin(s)`);

    return new Response(
      JSON.stringify({ success: true, recipients: adminEmails.length }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('[Hephaestus Alert] Error:', error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : 'Unknown error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
