import { motion } from 'framer-motion';
import { useState } from 'react';
import { BookOpen, Sparkles, Share2, Download } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';

export function StoryGenerator() {
  const [story, setStory] = useState({
    title: "Your Financial Journey This Week",
    chapters: [
      {
        title: "The Beginning",
        content: "This week started strong with a $500 paycheck deposit. You were determined to stick to your budget and make progress on your vacation goal.",
        mood: "optimistic"
      },
      {
        title: "The Challenge",
        content: "Mid-week brought unexpected car repairs ($350), testing your emergency fund. But you handled it without touching your savings goals!",
        mood: "resilient"
      },
      {
        title: "The Victory",
        content: "By week's end, you still managed to save $150 towards your vacation fund. Your dedication paid off, bringing you to 45% of your goal!",
        mood: "triumphant"
      }
    ]
  });

  const [isGenerating, setIsGenerating] = useState(false);

  const generateStory = async () => {
    setIsGenerating(true);
    toast.info('AI is crafting your financial story...');

    // Simulate AI generation
    setTimeout(() => {
      setIsGenerating(false);
      toast.success('Story generated!');
    }, 2000);
  };

  const shareStory = () => {
    toast.success('Story link copied to clipboard!');
  };

  const getMoodColor = (mood: string) => {
    switch (mood) {
      case 'optimistic': return 'border-blue-500/20 bg-blue-500/5';
      case 'resilient': return 'border-yellow-500/20 bg-yellow-500/5';
      case 'triumphant': return 'border-green-500/20 bg-green-500/5';
      default: return 'border-border bg-accent/50';
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="bg-card border border-border rounded-3xl p-6 shadow-lg"
    >
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-3">
          <div className="p-3 bg-primary/10 rounded-2xl">
            <BookOpen className="w-6 h-6 text-primary" />
          </div>
          <div>
            <h3 className="text-xl font-semibold text-foreground">Financial Story</h3>
            <p className="text-sm text-muted-foreground">AI-generated narrative</p>
          </div>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" size="icon" onClick={shareStory}>
            <Share2 className="w-4 h-4" />
          </Button>
          <Button variant="outline" size="icon">
            <Download className="w-4 h-4" />
          </Button>
        </div>
      </div>

      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        className="mb-6"
      >
        <div className="relative mb-6">
          <h2 className="text-3xl font-bold text-foreground mb-2">{story.title}</h2>
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <Sparkles className="w-4 h-4" />
            <span>Generated by AI • This week</span>
          </div>
        </div>

        <div className="space-y-6">
          {story.chapters.map((chapter, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.2 }}
              className={`border rounded-3xl p-6 ${getMoodColor(chapter.mood)}`}
            >
              <div className="flex items-center gap-3 mb-3">
                <div className="w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center">
                  <span className="text-lg font-bold text-primary">{i + 1}</span>
                </div>
                <h4 className="text-xl font-semibold text-foreground">{chapter.title}</h4>
              </div>
              <p className="text-foreground/80 leading-relaxed">{chapter.content}</p>
            </motion.div>
          ))}
        </div>
      </motion.div>

      <div className="flex gap-3">
        <Button
          onClick={generateStory}
          disabled={isGenerating}
          className="flex-1"
        >
          {isGenerating ? (
            <>
              <motion.div
                animate={{ rotate: 360 }}
                transition={{ duration: 2, repeat: Infinity, ease: 'linear' }}
              >
                <Sparkles className="w-4 h-4 mr-2" />
              </motion.div>
              Generating...
            </>
          ) : (
            <>
              <Sparkles className="w-4 h-4 mr-2" />
              Regenerate Story
            </>
          )}
        </Button>
      </div>

      <div className="mt-4 p-4 bg-accent/50 rounded-2xl">
        <p className="text-xs text-muted-foreground text-center">
          Stories are personalized based on your actual financial data and generated using AI
        </p>
      </div>
    </motion.div>
  );
}
