/**
 * BundleAnalysis - Admin dashboard for bundle size visualization
 */
import { AppLayout } from '@/components/layout/AppLayout';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Progress } from '@/components/ui/progress';
import { Badge } from '@/components/ui/badge';
import { Package, FileCode, AlertTriangle, TrendingDown, Layers } from 'lucide-react';
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip, BarChart, Bar, XAxis, YAxis } from 'recharts';

// Estimated bundle composition (would be generated by build analysis in production)
const BUNDLE_DATA = {
  total: {
    parsed: 2400,
    gzipped: 680,
  },
  chunks: [
    { name: 'vendor', parsed: 850, gzipped: 240, description: 'React, Router, TanStack Query' },
    { name: 'three', parsed: 520, gzipped: 145, description: 'Three.js + React Three Fiber' },
    { name: 'ui', parsed: 280, gzipped: 78, description: 'Radix UI, Shadcn components' },
    { name: 'charts', parsed: 220, gzipped: 62, description: 'Recharts, D3' },
    { name: 'pages', parsed: 380, gzipped: 105, description: 'Page components' },
    { name: 'utils', parsed: 150, gzipped: 50, description: 'Utilities, helpers, hooks' },
  ],
  largestDependencies: [
    { name: 'three', size: 520, trend: -5 },
    { name: 'react-dom', size: 130, trend: 0 },
    { name: 'recharts', size: 180, trend: -2 },
    { name: '@tanstack/react-query', size: 45, trend: 0 },
    { name: 'framer-motion', size: 110, trend: -8 },
    { name: 'date-fns', size: 75, trend: 0 },
  ],
  optimizationSuggestions: [
    {
      title: 'Lazy load Three.js',
      impact: 'high',
      savings: '~145KB gzipped',
      description: 'Load 3D components only when visible',
      implemented: true,
    },
    {
      title: 'Tree-shake date-fns',
      impact: 'medium',
      savings: '~20KB gzipped',
      description: 'Import only used functions',
      implemented: true,
    },
    {
      title: 'Code split heavy pages',
      impact: 'high',
      savings: '~80KB initial',
      description: 'Split Dashboard, Analytics, Coach',
      implemented: true,
    },
    {
      title: 'Replace moment with date-fns',
      impact: 'medium',
      savings: '~50KB gzipped',
      description: 'moment.js is larger than date-fns',
      implemented: true,
    },
  ],
};

const COLORS = ['#06b6d4', '#8b5cf6', '#f59e0b', '#10b981', '#ec4899', '#6366f1'];

export default function BundleAnalysis() {
  const pieData = BUNDLE_DATA.chunks.map(chunk => ({
    name: chunk.name,
    value: chunk.gzipped,
  }));

  return (
    <AppLayout>
      <div className="space-y-6 max-w-6xl mx-auto">
        <div>
          <h1 className="text-3xl font-bold tracking-tight flex items-center gap-3">
            <Package className="h-8 w-8 text-primary" />
            Bundle Analysis
          </h1>
          <p className="text-muted-foreground mt-2">
            Monitor and optimize JavaScript bundle sizes
          </p>
        </div>

        {/* Summary Cards */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <Card>
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-muted-foreground">Total Gzipped</p>
                  <p className="text-3xl font-bold">{BUNDLE_DATA.total.gzipped}KB</p>
                </div>
                <FileCode className="h-8 w-8 text-cyan-500" />
              </div>
              <Progress 
                value={(BUNDLE_DATA.total.gzipped / 1000) * 100} 
                className="mt-3 h-2"
              />
              <p className="text-xs text-muted-foreground mt-1">
                Target: &lt;500KB for optimal load
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-muted-foreground">Total Parsed</p>
                  <p className="text-3xl font-bold">{BUNDLE_DATA.total.parsed}KB</p>
                </div>
                <Layers className="h-8 w-8 text-violet-500" />
              </div>
              <Progress 
                value={(BUNDLE_DATA.total.parsed / 3000) * 100} 
                className="mt-3 h-2"
              />
              <p className="text-xs text-muted-foreground mt-1">
                Uncompressed JavaScript size
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-muted-foreground">Compression Ratio</p>
                  <p className="text-3xl font-bold">
                    {((1 - BUNDLE_DATA.total.gzipped / BUNDLE_DATA.total.parsed) * 100).toFixed(0)}%
                  </p>
                </div>
                <TrendingDown className="h-8 w-8 text-emerald-500" />
              </div>
              <p className="text-sm text-emerald-500 mt-3">Excellent compression</p>
            </CardContent>
          </Card>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Chunk Composition */}
          <Card>
            <CardHeader>
              <CardTitle>Bundle Composition</CardTitle>
              <CardDescription>Size breakdown by chunk (gzipped)</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="h-[250px]">
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie
                      data={pieData}
                      cx="50%"
                      cy="50%"
                      innerRadius={60}
                      outerRadius={100}
                      paddingAngle={2}
                      dataKey="value"
                      label={({ name, value }) => `${name}: ${value}KB`}
                      labelLine={false}
                    >
                      {pieData.map((_, index) => (
                        <Cell key={index} fill={COLORS[index % COLORS.length]} />
                      ))}
                    </Pie>
                    <Tooltip 
                      contentStyle={{ 
                        backgroundColor: 'hsl(var(--card))',
                        border: '1px solid hsl(var(--border))',
                        borderRadius: '8px',
                      }}
                    />
                  </PieChart>
                </ResponsiveContainer>
              </div>

              {/* Legend */}
              <div className="mt-4 grid grid-cols-2 gap-2">
                {BUNDLE_DATA.chunks.map((chunk, i) => (
                  <div key={chunk.name} className="flex items-center gap-2 text-sm">
                    <div 
                      className="h-3 w-3 rounded-full" 
                      style={{ backgroundColor: COLORS[i] }}
                    />
                    <span className="truncate">{chunk.name}</span>
                    <span className="text-muted-foreground ml-auto">{chunk.gzipped}KB</span>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* Largest Dependencies */}
          <Card>
            <CardHeader>
              <CardTitle>Largest Dependencies</CardTitle>
              <CardDescription>Top packages by size impact</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="h-[250px]">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart
                    data={BUNDLE_DATA.largestDependencies}
                    layout="vertical"
                    margin={{ left: 80 }}
                  >
                    <XAxis type="number" unit="KB" />
                    <YAxis dataKey="name" type="category" width={70} />
                    <Tooltip
                      contentStyle={{ 
                        backgroundColor: 'hsl(var(--card))',
                        border: '1px solid hsl(var(--border))',
                        borderRadius: '8px',
                      }}
                      formatter={(value: number) => [`${value}KB`, 'Size']}
                    />
                    <Bar dataKey="size" fill="hsl(var(--primary))" radius={4} />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Optimization Suggestions */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <AlertTriangle className="h-5 w-5 text-amber-500" />
              Optimization Checklist
            </CardTitle>
            <CardDescription>
              Implemented and pending optimizations
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {BUNDLE_DATA.optimizationSuggestions.map((suggestion, i) => (
                <div 
                  key={i}
                  className={`flex items-start gap-4 p-4 rounded-lg border ${
                    suggestion.implemented 
                      ? 'border-emerald-500/20 bg-emerald-500/5' 
                      : 'border-amber-500/20 bg-amber-500/5'
                  }`}
                >
                  <div className={`h-6 w-6 rounded-full flex items-center justify-center ${
                    suggestion.implemented ? 'bg-emerald-500' : 'bg-amber-500'
                  }`}>
                    {suggestion.implemented ? '✓' : '!'}
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center gap-2">
                      <span className="font-medium">{suggestion.title}</span>
                      <Badge 
                        variant={suggestion.impact === 'high' ? 'destructive' : 'secondary'}
                        className="text-xs"
                      >
                        {suggestion.impact} impact
                      </Badge>
                    </div>
                    <p className="text-sm text-muted-foreground mt-1">
                      {suggestion.description}
                    </p>
                    <p className="text-sm text-emerald-500 mt-1">
                      Potential savings: {suggestion.savings}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </AppLayout>
  );
}
